version: "3.8"

services:
  cipher-api:
    build: .
    container_name: cipher-api
    ports:
      - "8080:8080"
    environment:
      - CIPHER_KEY=this_is_really_long_key_ # 16 bytes, 24 bytes, or 32 bytes
    restart: unless-stopped