version: "3.8"

services:
  cipher-api:
    build: .
    container_name: cipher-api
    ports:
      - "8080:8080"
    environment:
      - CIPHER_KEY=change_this_secret_key
    restart: unless-stopped